### ISSUE TITLE
Question about handling assets in sbt

### ISSUE THREAD

**Issue by matanster** [sbt/sbt-web#138]
Not really a bug, but  trying out the following line in build.sbt as per [the readme](https://github.com/sbt/sbt-web#packaging-and-publishing):

```
(managedClasspath in Runtime) += (packageBin in Assets).value
```

I get the error: 

```
Reference to undefined setting:  web-assets:packageBin
```

I've added in plugins.sbt only the following, for sbt-web:

```
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "latest.release")
```

Any specific imports to be made?
What might be missing?

Also this piece from the same documentation yields an error:

```
WebKeys.packagePrefix in Assets := "public/"
```

**Comment by readren** [comment]
Have you enabled the plugin in the project in question? If not, do it with `enablePlugins(SbtWeb).
For example, to enable the SbtWeb plugin for the root project, you should have a line like this:
`lazy val root = (project in file(".")).enablePlugins(SbtWeb)`
to the "build.sbt" file.

Note that if you enable the play [2.4) plugin (with `enablePlugins(PlayScala)`) for a project, it's not necessary to enable the SbtWeb plugin because play already includes it.

**Comment by mkurz** [comment]
Seems unrelated.
