### ISSUE TITLE
Travis CI dropped

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-web#183]
Given the poor handling of the recent security incident (https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/) I'm suspending Travis CI integration indefinitely.

Let's move on to GitHub Actions.

**Comment by mkurz** [comment]
@eed3si9n Can you do me a favor and rename the `master` branch to `main` [here](https://github.com/sbt/sbt-web/branches)?
I don't have the power to do so.
I am going to set up github actions, publishing, etc. and we usually call the default branch main now.

Thanks!

**Comment by eed3si9n** [comment]
@mkurz Done.

**Comment by mkurz** [comment]
Thanks!

**Comment by mkurz** [comment]
@eed3si9n Actually, I am wondering: I am part of the https://github.com/orgs/sbt/teams/sbt-web team and this team does have admin rights on most sbt repos already anyway, like
* https://github.com/sbt/sbt-web-build-base/settings/access
* https://github.com/sbt/sbt-uglify/settings/access
* https://github.com/sbt/sbt-rjs/settings/access
* https://github.com/sbt/sbt-less/settings/access
* and many many more...

Wouldn't it make sense to also just add the sbt-web team as admins to this repo here? Looks like I am "just" moderator currently
* https://github.com/sbt/sbt-web/settings/access (I can not see this page)

And, since I am here, can you add the sbt-web team as admins to 
* sbt-digest (https://github.com/sbt/sbt-digest/settings/access)

as well?

I am in the process of overhauling most of these plugins (like publish them to maven central, etc.)

Thanks!

**Comment by eed3si9n** [comment]
sbt-web team can be exceptional, but generally I've been giving teams Maintain rights rather than Admin rights to avoid random person getting added to the write list (admins can add more committers) and adding to security vector, esp when automated publishing is configured.

**Comment by mkurz** [comment]
Fixed by #194
